KITS = {
    assault = {
        'Gameplay/Kits/RUAssault',
        'Gameplay/Kits/USAssault',
        'Gameplay/Kits/RUAssault_XP4',
        'Gameplay/Kits/USAssault_XP4',
    },
    engineer = {
        'Gameplay/Kits/RUEngineer',
        'Gameplay/Kits/USEngineer',
        'Gameplay/Kits/RUEngineer_XP4',
        'Gameplay/Kits/USEngineer_XP4',
    },
    support = {
        'Gameplay/Kits/RUSupport',
        'Gameplay/Kits/USSupport',
        'Gameplay/Kits/RUSupport_XP4',
        'Gameplay/Kits/USSupport_XP4',
    },
    recon = {
        'Gameplay/Kits/RURecon',
        'Gameplay/Kits/USRecon',
        'Gameplay/Kits/RURecon_XP4',
        'Gameplay/Kits/USRecon_XP4',
    },
}
-- 'Gameplay/Kits/<KIT>_GM' is for Gun Master gamemode and should not be added
-- 'Gameplay/Kits/<KIT>_SCV' is for Scavenger gamemode and should not be added

KIT_PRIMARY_WEAP_ID = 'ID_M_SOLDIER_PRIMARY'
KIT_SECONDARY_WEAP_ID = 'ID_M_SOLDIER_SECONDARY'
KIT_SPECIALIZATION_ID = 'ID_M_SOLDIER_SPECIALIZATION'
KIT_SOLDIER_GADGET1_ID = 'ID_M_SOLDIER_GADGET1'
KIT_SOLDIER_GADGET2_ID = 'ID_M_SOLDIER_GADGET2'

WEAP_CUSTOMIZATIONS = {
    'Weapons/A91/A91_Customization',
    'Weapons/AEK971/AEK971_Customization',
    'Weapons/AK74M/AK74M_Customization',
    'Weapons/AKS74u/AKS74u_Customization',
    'Weapons/AN94/AN94_Customization',
    'Weapons/ASVal/ASVal_Customizations',
    'Weapons/DAO-12/DAO-12_Customization',
    'Weapons/F2000/F2000_Customization',
    'Weapons/G36C/G36C_Customization',
    'Weapons/G3A3/G3A3_Customization',
    'Weapons/Glock18/Glock18_Customization',
    'Weapons/KH2002/KH2002_Customization',
    'Weapons/M1014/M1014_Customization',
    'Weapons/M16A4/M16A4_Customization',
    'Weapons/M240/M240_Customization',
    'Weapons/M249/M249_Customization',
    'Weapons/M27IAR/M27IAR_Customization',
    'Weapons/M39EBR/M39EBR_Customization',
    'Weapons/M40A5/M40A5_Customization',
    'Weapons/M416/M416_Customization',
    'Weapons/M4A1/M4A1_Customization',
    'Weapons/M60/M60_Customization',
    'Weapons/M82A3/M82_Customization',
    'Weapons/M93R/M93R_Customization',
    'Weapons/MagpulPDR/MagpulPDR_Customization',
    'Weapons/MK11/Mk11_Customization',
    'Weapons/Model98B/M98B_Customization',
    'Weapons/MP7/MP7_Customization',
    'Weapons/P90/P90_Customization',
    'Weapons/Pecheneg/Pecheneg_Customization',
    'Weapons/PP2000/PP2000_Customization',
    'Weapons/Remington870/870_Customization',
    'Weapons/RPK/RPK_Customization',
    'Weapons/SAIGA20K/Saiga_20k_Customization',
    'Weapons/SCAR-H/SCAR-H_Customization',
    'Weapons/SG553LB/SG553LB_Customization',
    'Weapons/SKS/SKS_Customization',
    'Weapons/SV98/SV98_Customization',
    'Weapons/SVD/SVD_Customization',
    'Weapons/Taurus44/Taurus44_Customization',
    'Weapons/Type88/Type88_Customization',
    'Weapons/UMP45/UMP45_Customization',
    'Weapons/USAS-12/USAS-12_Customization',
    'Weapons/XP1_FAMAS/FAMAS_Customization',
    'Weapons/XP1_HK53/HK53_Customization',
    'Weapons/XP1_Jackhammer/Jackhammer_Customization',
    'Weapons/XP1_L85A2/L85A2_Customization',
    'Weapons/XP1_L96/L96_Customization',
    'Weapons/XP1_MG36/MG36_Customization',
    'Weapons/XP1_PP-19/PP-19_Customization',
    'Weapons/XP1_QBB-95/QBB-95_Customization',
    'Weapons/XP1_QBU-88/QBU-88_Customization',
    'Weapons/XP1_QBZ-95B/QBZ-95B_Customization',
    'Weapons/XP2_ACR/ACR_Customization',
    'Weapons/XP2_HK417/HK417_Customization',
    'Weapons/XP2_JNG90/JNG90_Customization',
    'Weapons/XP2_L86/L86_Customization',
    'Weapons/XP2_LSAT/LSAT_Customization',
    'Weapons/XP2_MP5K/MP5K_Customization',
    'Weapons/XP2_MTAR/MTAR_Customization',
    'Weapons/XP2_SCAR-L/SCAR-L_Customization',
    'Weapons/XP2_SPAS12/SPAS12_Customization',
    'Weapons/XP2_SteyrAug/SteyrAug_Customization',
    'Weapons/XP4_Crossbow_Prototype/Crossbow_Customization'
}
